<?php
/* This is an autogenerated file from ShellMVC framework to help with code completion in some IDEs (built with  PHP Storm in mind.
This file will be auto genereated each time new models is cached and all content will be overwritten.
DO NOT MAKE MANUAL CHANGES TO THIS FILE
*/


/**
* @property int Id
* @property string PageTitle
* @property string NavigationTitle
* @property string Content
* @property int ShowInMenu
* @property int ProjectId
* @property int ClassId
* @property int MethodId
* @property int PropertyId
* @property int ParentDocumentId
* @property Document ParentDocument
**/
class Document{}


/**
* @property int Id
* @property string ExampleText
* @property string ExampleContent
* @property int SortOrder
* @property int IsActive
* @property int ProjectLanguageId
* @property int ProjectId
* @property int ClassId
* @property int MethodId
* @property int PropertyId
* @property ProjectLanguage ProjectLanguage
**/
class Example{}


/**
* @property int Id
* @property string TypeName
* @property int MethodId
* @property int SortIndex
* @property string Constraint
* @property Method Method
* @property Collection Methods
**/
class GenericType{}


/**
* @property int Id
* @property int ProjectClassId
* @property int InheritInterfaceId
* @property ProjectClass ProjectClass
* @property ProjectClass InheritInterface
**/
class InheritInterface{}


/**
* @property int Id
* @property string MethodName
* @property string ShortDescription
* @property string Description
* @property int IsStatic
* @property int AccessModifierId
* @property int ProjectClassId
* @property int ReturnTypeId
* @property int CustomModifiersId
* @property int ReturnGenericTypeId
* @property ProjectClass ProjectClass
* @property ProjectClass ReturnType
* @property GenericType ReturnGenericType
* @property Collection Parameters
**/
class Method{}


/**
* @property int Id
* @property string ParameterName
* @property string DefaultValue
* @property int MethodId
* @property int TypeId
* @property int ReturnGenericTypeId
* @property int IsExtension
* @property Method Method
* @property ProjectClass Type
**/
class Parameter{}


/**
* @property int Id
* @property int ProjectCategoryId
* @property int ProjectLanguageId
* @property string ProjectName
* @property string ShortDescription
* @property string Description
* @property int IsActive
* @property string TitleName
* @property ProjectCategory ProjectCategory
* @property ProjectLanguage ProjectLanguage
* @property Collection ProjectClasses
**/
class Project{}


/**
* @property int Id
* @property string Name
* @property int IsActive
**/
class ProjectCategory{}


/**
* @property int Id
* @property string ClassName
* @property string ShortDescription
* @property string Description
* @property string Namespace
* @property string ExternalSource
* @property int BaseClassId
* @property int ProjectId
* @property int IsPrimitive
* @property int CustomModifiersId
* @property ProjectClass BaseClass
* @property Project Project
* @property Collection ProjectClasses
**/
class ProjectClass{}


/**
* @property int Id
* @property string DisplayName
* @property string ClassName
* @property int IsActive
**/
class ProjectLanguage{}


/**
* @property int Id
* @property string PropertyName
* @property string ShortDescription
* @property string Description
* @property int IsStatic
* @property int AccessModifierId
* @property int ProjectClassId
* @property int TypeId
* @property int CustomModifiersId
* @property ProjectClass ProjectClass
* @property ProjectClass Type
**/
class Property{}


/**
* @property int Id
* @property string VersionNumber
* @property string ReleaseDate
* @property string Content
* @property int ProjectId
* @property Project Project
**/
class ReleaseNotes{}


/**
* @property int Id
* @property int ProjectId
* @property int ClassId
* @property int MethodId
* @property int PropertyId
* @property string DisplayName
* @property string Link
**/
class SeeAlsoLink{}


/**
* @property int Id
* @property string Identifier
* @property string Content
**/
class StaticBlock{}


/**
* @property int Id
* @property int ShellUserId
**/
class LocalUser{}

