<?php

const PHP_DOC_MODEL_FILE = './Application/PhpDoc/ModelDocumentation.php';

class PhpDocWriter
{
    /* @var ModelHelper ModelHelper*/
    public $ModelHelper;

    public function __construct($modelHelper)
    {
        $this->ModelHelper = $modelHelper;
    }

    public function WritePhpDocForModelCollection($modelCollections)
    {

    }

    public function WritePhpDocForModels($modelCaches)
    {
        if ($modelCaches == null) {
            return;
        }
        $result = array();

        $result = array_merge($result, $this->GetModelsPhpDocHeader());

        foreach ($modelCaches as $key => $modelCache) {
            $result = array_merge($result, $this->GetPhpDocForModel($key, $modelCache));
        }

        $fileContent = implode("\n", $result);
        $saveResult = file_put_contents(PHP_DOC_MODEL_FILE, $fileContent);
    }

    private function GetModelsPhpDocHeader()
    {
        return array(
            '<?php',
            '/* This is an autogenerated file from ShellMVC framework to help with code completion in some IDEs (built with  PHP Storm in mind.',
            'This file will be auto genereated each time new models is cached and all content will be overwritten.',
            'DO NOT MAKE MANUAL CHANGES TO THIS FILE',
            '*/',
            '',
            ''
        );
    }

    private function GetPhpDocForModel($key, $modelCache)
    {
        $result = array();

        $result[] = '/**';
        $className = $key;
        foreach ($modelCache['Columns'] as $columnName => $column) {
            $result[] = '* @property ' . $this->GetPropertyType($column['Type']) . ' ' . $columnName;
        }

        foreach ($modelCache['References'] as $referenceName => $reference) {
            $result[] = '* @property ' . $this->ModelHelper->GetModelName($reference['TableName']) . ' ' . $this->CreateReferenceName($referenceName);
        }

        foreach($modelCache['ReversedReferences'] as $referenceName => $reference){
            $result[] = '* @property Collection ' . $referenceName;
        }

        $result[] = '**/';
        $result[] = "class $className{}";

        // Adds two empty line
        $result[] = '';
        $result[] = '';

        return $result;
    }

    private function GetPropertyType($dataType)
    {
        if(strpos($dataType, 'int') !== false){
            return 'int';
        }else if(strpos($dataType, 'varchar') !== false){
            return 'string';
        }else{
            return 'mixed';
        }
    }

    protected function CreateReferenceName($columnName)
    {
        if(endsWith($columnName, 'Id')){
            return replaceLastOccurence($columnName, 'Id', '');
        } else if(endsWith($columnName, '_id')){
            return replaceLastOccurence($columnName, '_id', '');
        }else{
            return $columnName + 'Object';
        }
    }
}